import { StyleSheet } from 'react-native';

export const StylesBase = StyleSheet.create({
  'carefrees-form': {
    fontSize: 14,
  },
  'carefrees-form-layout': {
    width: '100%',
    borderRadius: 4,
    paddingBottom: 8,
    position: 'relative',
  },
  'carefrees-form-layout.bordered': {
    borderColor: '#e0e0e0',
    borderWidth: 1,
    borderStyle: 'solid',
  },
  'carefrees-form-layout-header': {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    borderBottomColor: '#e0e0e0',
    borderBottomWidth: 1,
    paddingTop: 5,
    paddingBottom: 5,
    marginBlockEnd: 4,
    paddingInlineStart: 2,
    paddingInlineEnd: 2,
  },
  'carefrees-form-layout-header.bordered': {
    paddingInlineStart: 8,
    paddingInlineEnd: 8,
  },
  isAllColSpan: {
    width: '100%',
  },
  title: {
    fontSize: 16,
    fontWeight: 600,
    color: '#1d2129',
  },
  'carefrees-form-layout-header-title': {
    fontSize: 16,
    fontWeight: 600,
    color: '#1d2129',
  },
  extra: {
    fontSize: 14,
    fontWeight: 500,
    color: '#1d2129',
  },
  'carefrees-form-layout-header-extra': {
    fontSize: 14,
    fontWeight: 500,
    color: '#1d2129',
  },
  'carefrees-form-layout-body': {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingInlineStart: 2,
    paddingInlineEnd: 2,
    gap: 2,
  },
  'carefrees-form-item': {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 8,
    color: 'rgba(0, 0, 0, 0.88)',
  },
  'carefrees-form-item.only-rule-style': {
    padding: 0,
  },
  'carefrees-form-item-container': {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    height: '100%',
    flex: 1,
  },
  'carefrees-form-item-container.left': {
    flexDirection: 'row',
    gap: 8,
    textAlign: 'left',
  },
  'carefrees-form-item-label-warp.left': {
    justifyContent: 'flex-end',
  },
  'carefrees-form-item-container.between': {
    gap: 8,
    textAlign: 'left',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  'carefrees-form-item-body-com.between': {
    justifyContent: 'flex-end',
    textAlign: 'right',
  },
  'carefrees-form-item-label-warp': {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  'carefrees-form-item-label-warp.minHeight': {
    minHeight: 32,
    alignItems: 'center',
  },
  'carefrees-form-item-label': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    position: 'relative',
    fontSize: 14,
    color: 'rgba(0, 0, 0, 0.88)',
  },
  'carefrees-form-item-label.show-colon': {
    textAlign: 'center',
    margin: 0,
    marginInlineEnd: 2,
    marginInlineStart: 2,
  },
  'carefrees-form-item-label.required': {
    color: 'red',
    margin: 0,
    marginInlineEnd: 2,
  },
  'carefrees-form-item-body': {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 4,
    flex: 1,
  },
  'carefrees-form-item-body-input': {
    width: '100%',
    flex: 1,
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  'carefrees-form-item-body-input.input-bordered': {
    borderWidth: 0,
    borderBottomColor: '#e0e0e0',
    borderBottomWidth: 1,
    borderStyle: 'solid',
  },
  'carefrees-form-item-body-help': {
    width: '100%',
  },
  'carefrees-form-item-body-error': {
    position: 'absolute',
    width: '100%',
    color: 'red',
    top: 'auto',
    left: 0,
    right: 0,
    bottom: -16,
    paddingTop: 2,
    zIndex: 10,
    fontSize: 12,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  'error-text': {
    fontSize: 12,
    color: 'red',
  },
  'carefrees-form-item-body-error.right-bottom': {
    top: 'auto',
    left: 0,
    right: 0,
    bottom: -16,
    justifyContent: 'flex-end',
  },
  'carefrees-form-item-body-error.top-left': {
    top: -16,
    left: 0,
    right: 0,
    bottom: 'auto',
    justifyContent: 'flex-start',
  },
  'carefrees-form-item-body-error.top-right': {
    top: -16,
    left: 0,
    right: 0,
    bottom: 'auto',
    justifyContent: 'flex-end',
  },
  'carefrees-form-item-extra': {},
  fontSize12: {
    fontSize: 12,
  },
  fontSize14: {
    fontSize: 14,
  },
});
